# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Discipline' do
pod 'Material', '~> 1.0'
end

target 'DisciplineTests' do

end

target 'DisciplineUITests' do

end

